name: CI/CD Pipeline 2

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'  # Specify the distribution here (e.g., adopt, zulu, temurin)
        java-version: '8'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and tag Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/intens-api-2022:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/intens-api-2022:latest
